# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24c96096d687170db038f284a22596bf0e8ba9ece7423cf4f4f6a99e358e94a5d8e5e6d5a2b7a57ba00e65340ae756e75807aa65eab8a971d598e72f4d84b3ac

test:
  secret_key_base: 8c584aa7f5c71e1ffa0447db2734d09b96f93b3ac42b5120323c4421ef028d6258f74a7b84ae36d9135ecc8b1f2fc42125b3d0853afe444ca027457fce13aff4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
